config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  get 'sessions/new'
  get 'plans/:plan_id/todos', to: 'todos#new' #todoの新規作成を失敗した直後にページを更新すると、ルーティングエラーが発生するので、その対策です。
  get 'categorys/:category_id/questions/:question_id/answers', to: 'answers#new' #上記と同じくルーティングエラー対策です。
  get 'users', to: 'users#new' #上記と同じくルーティングエラー対策です。
  get 'categorys/:category_id/qs/:q_id/qcontents', to: 'qcontents#new' #上記と同じくルーティングエラー対策です。

  resources :users, only: [:new,:create,:show]
  resources :plans, only: [:new,:create,:show,:update] do
    resources :todos, only: [:new,:create,:edit,:update,:destroy]
  end
  namespace :administrator do
    resources :users, only: [:index]
  end
  
  resources :categorys do
    collection do
      get :qindex
    end
    resources :questions do
      collection do
        get :search
      end
      resources :answers, only: [:new,:create,:destroy] do
        collection do
          get :search
        end
      end
    end
  end

  resources :tweets,only: [:index,:new,:create,:destroy] do
    collection do
      get :search
    end
  end
  
  resources :study_times,only: [:new,:create,:show] do
    member do
      get :newfinish
    end
  end
  
  resources :categorys do
    resources :qs do
      resources :qcontents do
      end
    end
  end
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :ans, presence: true,length: {in: 1..500}
  
  belongs_to :question
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,length: {in: 1..100}
  
  has_many :questions, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :qs, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  def start_time
    self.plandate
  end
  
  validates :user_id, presence: true
  validates :plandate, presence: true
  
  belongs_to :user
  has_many :todos
  has_many :study_time

   
  
end

app/models/q.rb
class Q < ApplicationRecord
  validates :qtitle, presence: true,length: {in: 1..250}
  
  belongs_to :category
  belongs_to :user
  has_many :qcontents
end

app/models/qcontent.rb
class Qcontent < ApplicationRecord
  validates :qsentence, presence: true,length: {in: 1..250}
  validates :choice1, presence: true,length: {in: 1..250}
  validates :choice2, presence: true,length: {in: 1..250}
  validates :choice3, presence: true,length: {in: 1..250}
  
  belongs_to :q
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true,length: {in: 1..500}
  validates :title, presence: true,length: {in: 1..500}
  
  belongs_to :category
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  
def start_time
  self.studydate
end
  
  belongs_to :user
  belongs_to :plan
  
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  
  validates :plan_id, presence: true
  validates :user_id, presence: true
  validates :list, presence: true,length: {in: 1..500}
  
  belongs_to :plan
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true,length: {in: 1..100}
  
  belongs_to :user
  belongs_to :category
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {in: 8..32}, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i} 
  validates :password_confirmation,length: {in: 8..32}
  
  has_many :plans
  has_many :todos
  has_many :questions
  has_many :answers
  #has_many :plan_todos, through: :plans, source: 'todo'
  has_many :tweets
  has_many :study_times
  has_many :qs

  has_secure_password
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  def index
    @qs = Q.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end
  
  def new
    @q = Q.new
    @category = Category.find(params[:category_id])
  end
  
  def create
    @q = Q.new(q_params)
    if @q.save
      redirect_to new_category_q_qcontent_path(category_id: @q.category_id, q_id: @q.id), success: '続いてクイズの内容の作成をしてください'
    else
      flash.now[:danger] = "クイズの作成に失敗しました"
      @category = @q.category
      render 'new'
    end
  end
  
  def show
    @q = Q.find(params[:id])
    @qcontents = @q.qcontents
    gon.qcontents = @qcontents
  end
  
  private
  def q_params
    params.require(:q).permit(:category_id, :user_id, :qtitle)
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to category_questions_path(params[:category_id]),success: '質問を投稿しました'
    else
      flash.now[:denger] = '質問の投稿に失敗しました'
      @category = @question.category
      render 'new'
    end
  end

  def index
    @category = Category.find(params[:category_id])
  end

  def show
    @question = Question.find(params[:id])
  end
  
  def search
    @questions = Question.where(user_id: current_user.id)
  end
  
  def edit
    @question = Question.find(params[:id])
    # @category = Category.find(params[:category_id])
  end
  
  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.content = params[:question][:content]
    if @question.save
      redirect_to search_category_questions_path(category_id: @question.category_id),success: '質問を更新しました'
    else
      flash.now[:denger] = '更新に失敗しました'
      render 'edit'
    end
  end
  
  
  #def destroy
   # question = Question.find(params[:id])
    #question.destroy
    #redirect_to questions_search_path,success:'質問を削除しました'
  #end
  
  private
  def question_params
    params.require(:question).permit(:category_id,:title,:content)
  end
    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/qcontents_helper.rb
module QcontentsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/edit.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @question, url: category_question_path(category_id: @question.category_id, id: @question.id) , method: :patch do |f| %>
          <div class="form-group text-white">
            <%= f.label "題名" %>
            <%= f.text_area :title, class: 'form-control input-sm margin20'%>
            <%= f.label "内容" %>
            <%= f.text_area :content, class: 'form-control input-lg' %>
          </div>
          <div class="col-md-4 col-md-offset-4">
            <%= f.submit '更新', class: 'btn btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 text-white text-center margin40">
        <h1>質問一覧</h1>
      </div>
      <div class="col-md-offset-3 col-md-6">
            <% @category.questions.each do|question| %>
              <%= link_to question.title,category_question_path(@category,question),class: 'btn btn-block btn-white' %>
            <% end %>
      <%= link_to '質問を投稿する',new_category_question_path(category_id: @category.id),class:'text-white text-left' %>
     </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for [@category,@question] do |f| %>
          <div class="form-group">
            <% if logged_in? %>
              <%= f.label "題名", class: 'text-white' %>
              <%= f.text_area :title, class: 'form-control input-sm margin20' %>
              <%= f.label "内容", class: 'text-white' %>
              <%= f.text_area :content, class: 'form-control input-lg' %>
              <%= f.hidden_field :category_id, :value => @category.id %>
          </div>
          <div class="col-md-offset-4 col-md-4">
              <%= f.submit '投稿', class: 'btn btn-block' %>
          </div>
            <% else %>
          <div class="col-md-12 ">
              <h1 class="text-white text-center"><%= "投稿はログイン後に行えます"%></h1>
          </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/search.html.erb
<div class="wrapper-stanard text-white">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 text-center margin40">
        <h1>質問一覧</h1>
      </div>
      <% @questions.each do|question| %>
        <div class="col-md-12 text-left">
          <h3>題名：<%= question.title %></h3>
          <h3>質問内容</h3>
          <p>
            &nbsp;&nbsp;<%= question.content%>
            &nbsp;&nbsp;<%= link_to '編集',edit_category_question_path(category_id: question.category_id,id: question.id) %>
          </p>
          <br>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <h1 class="text-white text-center margin40"><%= @question.title %></h1>
      </div>
      <div class="col-md-offset-1 col-md-10 col-md-offset-1">
        <h2 class="text-white text-left">内容</h2>
        <h3 class="text-white text-left margin40">&nbsp;&nbsp;<%= @question.content %></h3>
        <h2 class="text-white text-left">回答</h2>
        <ol class="text-white">
          <% @question.answers.each do|answer|%>
            <li class="margin20">
              <%= answer.ans %>
              <% if logged_in? %>
                <%= "@" %>
                <%= answer.user.name %>
              <% end %>
            </li>
          <% end %>
        </ol>
          <div class=" col-md-offset-4 col-md-4 col-md-offset-4 text-center">
            <% if logged_in? %>
              <%= link_to 'この質問に回答する',new_category_question_answer_path(category_id: @question.category_id, question_id: @question.id),class: 'btn btn-block btn-white' %>
            <% end %>
          </div>
       </div>
     </div>
  </div>
</div>