config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  get 'sessions/new'
  get 'plans/:plan_id/todos', to: 'todos#new' #todoの新規作成を失敗した直後にページを更新すると、ルーティングエラーが発生するので、その対策です。
  get 'categorys/:category_id/questions/:question_id/answers', to: 'answers#new' #上記と同じくルーティングエラー対策です。
  get 'users', to: 'users#new' #上記と同じくルーティングエラー対策です。
  get 'categorys/:category_id/qs/:q_id/qcontents', to: 'qcontents#new' #上記と同じくルーティングエラー対策です。

  resources :users, only: [:new,:create,:show]
  resources :plans, only: [:new,:create,:show,:update] do
    resources :todos, only: [:new,:create,:edit,:update,:destroy]
  end
  namespace :administrator do
    resources :users, only: [:index]
  end
  
  resources :categorys do
    collection do
      get :qindex
    end
    resources :questions do
      collection do
        get :search
      end
      resources :answers, only: [:new,:create,:destroy] do
        collection do
          get :search
        end
      end
    end
  end

  resources :tweets,only: [:index,:new,:create,:destroy] do
    collection do
      get :search
    end
  end
  
  resources :study_times,only: [:new,:create,:show] do
    member do
      get :newfinish
    end
  end
  
  resources :categorys do
    resources :qs do
      resources :qcontents do
      end
    end
  end
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :ans, presence: true,length: {in: 1..500}
  
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,length: {in: 1..100}
  
  has_many :questions, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :qs, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  def start_time
    self.plandate
  end
  
  validates :user_id, presence: true
  validates :plandate, presence: true
  
  belongs_to :user
  has_many :todos
  has_many :study_time

   
  
end

app/models/q.rb
class Q < ApplicationRecord
  validates :qtitle, presence: true,length: {in: 1..250}
  
  belongs_to :category
  belongs_to :user
  has_many :qcontents
end

app/models/qcontent.rb
class Qcontent < ApplicationRecord
  validates :qsentence, presence: true,length: {in: 1..250}
  validates :choice1, presence: true,length: {in: 1..250}
  validates :choice2, presence: true,length: {in: 1..250}
  validates :choice3, presence: true,length: {in: 1..250}
  
  belongs_to :q
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true,length: {in: 1..500}
  validates :title, presence: true,length: {in: 1..500}
  
  belongs_to :category
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  
def start_time
  self.studydate
end
  
  belongs_to :user
  belongs_to :plan
  
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  
  validates :plan_id, presence: true
  validates :user_id, presence: true
  validates :list, presence: true,length: {in: 1..500}
  
  belongs_to :plan
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true,length: {in: 1..100}
  
  belongs_to :user
  belongs_to :category
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {in: 8..32}, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i} 
  validates :password_confirmation,length: {in: 8..32}
  
  has_many :plans
  has_many :todos
  has_many :questions
  has_many :answers
  #has_many :plan_todos, through: :plans, source: 'todo'
  has_many :tweets
  has_many :study_times
  has_many :qs

  has_secure_password
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  def index
    @qs = Q.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end
  
  def new
    @q = Q.new
    @category = Category.find(params[:category_id])
  end
  
  def create
    @q = Q.new(q_params)
    if @q.save
      redirect_to new_category_q_qcontent_path(category_id: @q.category_id, q_id: @q.id), success: '続いてクイズの内容の作成をしてください'
    else
      flash.now[:danger] = "クイズの作成に失敗しました"
      @category = @q.category
      render 'new'
    end
  end
  
  def show
    @q = Q.find(params[:id])
    @qcontents = @q.qcontents
    gon.qcontents = @qcontents
  end
  
  private
  def q_params
    params.require(:q).permit(:category_id, :user_id, :qtitle)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/qcontents_helper.rb
module QcontentsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/qs/index.html.erb
<div class="wrapper-stanard text-center">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <h1 class="text-white margin40">クイズ</h1>
      </div>
      <% if logged_in? %>
        <div class="col-md-offset-3 col-md-6 col-md-offset-3 text-right margin30">
          <%= link_to "クイズを作成する", new_category_q_path(category_id: @category.id)%>
        </div>
      <% end %>
      <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <% @qs.each do |q| %>
          <%= link_to q.qtitle, category_q_path(category_id: q.category.id, id: q.id),class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/qs/new.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @q, url: category_qs_path(category_id: @category.id), method: :post do |f| %>
          <div class="form-group">
            <% if logged_in? %>
              <%= f.label "題名", class: 'text-white' %>
              <%= f.text_field :qtitle, class: 'form-control input-sm margin20' %>
              <%= f.hidden_field :category_id, :value => @category.id %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
          </div>
          <div class="col-md-offset-4 col-md-4">
              <%= f.submit '問題文と選択肢の作成へ進む', class: 'btn btn-block' %>
          </div>
            <% else %>
          <div class="col-md-12 ">
              <h1 class="text-white text-center"><%= "クイズの作成はログイン後に行えます"%></h1>
          </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/qs/show.html.erb
<div class="wrapper-stanard text-left text-white">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-md-offset-3 margin40" id="quest">
      </div>
      <ul id="choices" class="col-md-offset-3 col-md-6 col-md-offset-3 margin30">
        <!--<li class="col-md-offset-3 col-md-6 col-md-offset-3 margin20" id="choices1">-->
        <!--</li>-->
        <!--<li class="col-md-offset-3 col-md-6 col-md-offset-3 margin20" id="choices2">-->
        <!--</li>-->
        <!--<li class="col-md-offset-3 col-md-6 col-md-offset-3 margin20" id="choices3">-->
        <!--</li>-->
      </ul>
      <div class="col-md-offset-5 col-md-2 col-md-offset-5 margin20 disabled" id="next">次の問題</div>
      <div id = "resultNumber" class="hidden">
        <p></p>
        <a href="">再挑戦</a>
      </div>
      
      
      
      
      
      
      <!--<% @q.qcontents.each do |qcontent| %>-->
      <!--    <div class="col-md-offset-3 col-md-6 col-md-offset-3" id="question">-->
      <!--      <%= qcontent.qsentence %>-->
      <!--    </div>-->
      <!--    <div class="col-md-offset-3 col-md-6 col-md-offset-3" id="choices">-->
      <!--      <%= qcontent.choice1 %>-->
      <!--    </div>-->
      <!--    <div class="col-md-offset-3 col-md-6 col-md-offset-3" id="choices">-->
      <!--      <%= qcontent.choice2 %>-->
      <!--    </div>-->
      <!--    <div class="col-md-offset-3 col-md-6 col-md-offset-3" id="choices">-->
      <!--      <%= qcontent.choice3 %>-->
      <!--    </div>-->
      <!--    <div class="col-md-offset-5 col-md-2 col-md-offset-5 margin20" id="btn">次の問題</div>-->
      <!--<% end %>-->
    </div>
  </div>
</div>