config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  get 'sessions/new'
  get 'plans/:plan_id/todos', to: 'todos#new' #todoの新規作成を失敗した直後にページを更新すると、ルーティングエラーが発生するので、その対策です。
  get 'categorys/:category_id/questions/:question_id/answers', to: 'answers#new' #上記と同じくルーティングエラー対策です。
  get 'users', to: 'users#new' #上記と同じくルーティングエラー対策です。
  get 'categorys/:category_id/qs/:q_id/qcontents', to: 'qcontents#new' #上記と同じくルーティングエラー対策です。

  resources :users, only: [:new,:create,:show]
  resources :plans, only: [:new,:create,:show,:update] do
    resources :todos, only: [:new,:create,:edit,:update,:destroy]
  end
  namespace :administrator do
    resources :users, only: [:index]
  end
  
  resources :categorys do
    collection do
      get :qindex
    end
    resources :questions do
      collection do
        get :search
      end
      resources :answers, only: [:new,:create,:destroy] do
        collection do
          get :search
        end
      end
    end
  end

  resources :tweets,only: [:index,:new,:create,:destroy] do
    collection do
      get :search
    end
  end
  
  resources :study_times,only: [:new,:create,:show] do
    member do
      get :newfinish
    end
  end
  
  resources :categorys do
    resources :qs do
      resources :qcontents do
      end
    end
  end
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :ans, presence: true,length: {in: 1..500}
  
  belongs_to :question
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,length: {in: 1..100}
  
  has_many :questions, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :qs, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  def start_time
    self.plandate
  end
  
  validates :user_id, presence: true
  validates :plandate, presence: true
  
  belongs_to :user
  has_many :todos
  has_many :study_time

   
  
end

app/models/q.rb
class Q < ApplicationRecord
  validates :qtitle, presence: true,length: {in: 1..250}
  
  belongs_to :category
  belongs_to :user
  has_many :qcontents
end

app/models/qcontent.rb
class Qcontent < ApplicationRecord
  validates :qsentence, presence: true,length: {in: 1..250}
  validates :choice1, presence: true,length: {in: 1..250}
  validates :choice2, presence: true,length: {in: 1..250}
  validates :choice3, presence: true,length: {in: 1..250}
  
  belongs_to :q
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true,length: {in: 1..500}
  validates :title, presence: true,length: {in: 1..500}
  
  belongs_to :category
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  
def start_time
  self.studydate
end
  
  belongs_to :user
  belongs_to :plan
  
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  
  validates :plan_id, presence: true
  validates :user_id, presence: true
  validates :list, presence: true,length: {in: 1..500}
  
  belongs_to :plan
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true,length: {in: 1..100}
  
  belongs_to :user
  belongs_to :category
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {in: 8..32}, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i} 
  validates :password_confirmation,length: {in: 8..32}
  
  has_many :plans
  has_many :todos
  has_many :questions
  has_many :answers
  #has_many :plan_todos, through: :plans, source: 'todo'
  has_many :tweets
  has_many :study_times
  has_many :qs

  has_secure_password
end

app/controllers/administrator/users_controller.rb
class Administrator::UsersController < ApplicationController
 before_action :admin_user
  def index
  end
    
private
    def admin_user
      redirect_to(root_url) unless current_user.administrator?
    end
  
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  def index
    @qs = Q.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end
  
  def new
    @q = Q.new
    @category = Category.find(params[:category_id])
  end
  
  def create
    @q = Q.new(q_params)
    if @q.save
      redirect_to new_category_q_qcontent_path(category_id: @q.category_id, q_id: @q.id), success: '続いてクイズの内容の作成をしてください'
    else
      flash.now[:danger] = "クイズの作成に失敗しました"
      @category = @q.category
      render 'new'
    end
  end
  
  def show
    @q = Q.find(params[:id])
    @qcontents = @q.qcontents
    gon.qcontents = @qcontents
  end
  
  private
  def q_params
    params.require(:q).permit(:category_id, :user_id, :qtitle)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path,success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render 'new'
    end
  end
  
  def show
    @tweet = Tweet.new
    @category = Category.all
    @study_times = StudyTime.where(user_id: current_user.id)
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
  
end

app/helpers/administrator/users_helper.rb
module Administrator::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/qcontents_helper.rb
module QcontentsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrator/users/index.html.erb
<div class="wrapper-stanard text-center">
  <div class="container container-standard">
    <h1 class="text-white">学習カテゴリー　追加</h1>
    <div class="row">
      <div class="col-md-offset-5 col-md-2 col-md-offset-5 text-center">
            <%= link_to '追加画面',new_category_path,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">学習掲示板　〜あなたの勉強をサポート〜</h1>
    <h2 class="text-white">ここでは、あなたの学習計画の作成、学習に関する質問・回答を投稿できます！</h2>
    <div class="row">
      <div class="col-md-3">
        <%= link_to '新規会員登録',new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ログイン',login_path,class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to '学習計画の作成', '#',class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to '質問掲示板', '#',class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ツイート', '#',class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-offset-4 col-md-4" >
        <h1 class="text-white text-center">新規登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label "お名前", class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label "メールアドレス", class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label "パスワード", class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label "パスワード（確認用）", class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="top-user-show-wrapper">
  <div class="container-standard">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>マイページ</h1>
      </div>
      
      <div class="col-md-12 text-black text-left">
        <h2>勉強時間カレンダー</h2>
      </div>
      
      <div class="col-md-12">
        <%= month_calendar events: @study_times do |date,study_times| %>
          <%= date %>
          <% a = 0 %>
          <% b = "" %>
          <% study_times.each do |study_time| %>
            <% if !study_time.finish.nil? %>
              <% a += study_time.finish - study_time.start %>
            <% end %>
            <% if !study_time.plan.achieve.nil? %>
              <% b = study_time.plan.achieve %>
            <% end %>
          <% end %>
          <br>
          <%= Time.at(a).utc.strftime('%-H時間%-M分%-S秒') %>
          <br>
          <%= "目標達成度:#{b}" %>
          <br>
        <% end %>
      </div>
 
      <% if created_question?%>
      <div class="col-md-12 text-left">
        <h3>
          <%= link_to '投稿した質問',search_category_questions_path(category_id: current_question.category_id) %>
        </h3>
      </div>
      <% else %>
      <div class="col-md-12 text-left">
        <h3>質問掲示板へ投稿すれば、質問をここで確認できるよ！</h3>
      </div>
      <% end %>
      
      <% if created_answer?%>
      <div class="col-md-12 text-left">
        <h3>
          <%= link_to '投稿した回答',search_category_question_answers_path(category_id: current_answer.question.category_id,question_id: current_answer.question_id) %>
        </h3>
      </div>
      <% else %>
      <div class="col-md-12 text-left">
        <h3>質問掲示板へ投稿すれば、回答をここで確認できるよ！</h3>
      </div>
      <% end %>
    
      <% if created_tweet?%>
      <div class="col-md-12 text-left margin20">
        <h3>
          <%= link_to '投稿したツイート',search_tweets_path(user_id: current_user.id) %>
        </h3>
      </div>
      <% else %>
      <div class="col-md-12 text-left margin20">
        <h3>ツイートを投稿すれば、自分の投稿したツイートをここで確認できるよ！</h3>
      </div>
      <% end %>
  
      <div class="col-md-12 text-left">
        <h3>ツイート　〜自由に発言しよう！〜</h3>
      </div>
      <div class="col-md-6 text-left">
       <%= form_for @tweet do |f| %>
        <div class="form-group">
          <%= f.collection_select(:category_id, @category, :id, :name, :prompt => "カテゴリ選択") %>
          <%= f.text_area :text, class: 'form-control input-lg' %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </div>
        <div class="col-md-offset-4 col-md-4 text-left">
          <%= f.submit '発言する', class: 'btn-block' %>
        </div>
       <% end %>
      </div>
      
    </div>
  </div>
</div>