config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  get 'sessions/new'
  get 'plans/:plan_id/todos', to: 'todos#new' #todoの新規作成を失敗した直後にページを更新すると、ルーティングエラーが発生するので、その対策です。
  get 'categorys/:category_id/questions/:question_id/answers', to: 'answers#new' #上記と同じくルーティングエラー対策です。
  get 'users', to: 'users#new' #上記と同じくルーティングエラー対策です。
  get 'categorys/:category_id/qs/:q_id/qcontents', to: 'qcontents#new' #上記と同じくルーティングエラー対策です。

  resources :users, only: [:new,:create,:show]
  resources :plans, only: [:new,:create,:show,:update] do
    resources :todos, only: [:new,:create,:edit,:update,:destroy]
  end
  namespace :administrator do
    resources :users, only: [:index]
  end
  
  resources :categorys do
    collection do
      get :qindex
    end
    resources :questions do
      collection do
        get :search
      end
      resources :answers, only: [:new,:create,:destroy] do
        collection do
          get :search
        end
      end
    end
  end

  resources :tweets,only: [:index,:new,:create,:destroy] do
    collection do
      get :search
    end
  end
  
  resources :study_times,only: [:new,:create,:show] do
    member do
      get :newfinish
    end
  end
  
  resources :categorys do
    resources :qs do
      resources :qcontents do
      end
    end
  end
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :ans, presence: true,length: {in: 1..500}
  
  belongs_to :question
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,length: {in: 1..100}
  
  has_many :questions, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :qs, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  def start_time
    self.plandate
  end
  
  validates :user_id, presence: true
  validates :plandate, presence: true
  
  belongs_to :user
  has_many :todos
  has_many :study_time

   
  
end

app/models/q.rb
class Q < ApplicationRecord
  validates :qtitle, presence: true,length: {in: 1..250}
  
  belongs_to :category
  belongs_to :user
  has_many :qcontents
end

app/models/qcontent.rb
class Qcontent < ApplicationRecord
  validates :qsentence, presence: true,length: {in: 1..250}
  validates :choice1, presence: true,length: {in: 1..250}
  validates :choice2, presence: true,length: {in: 1..250}
  validates :choice3, presence: true,length: {in: 1..250}
  
  belongs_to :q
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true,length: {in: 1..500}
  validates :title, presence: true,length: {in: 1..500}
  
  belongs_to :category
  belongs_to :user
  has_many :answers, dependent: :destroy
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  
def start_time
  self.studydate
end
  
  belongs_to :user
  belongs_to :plan
  
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  
  validates :plan_id, presence: true
  validates :user_id, presence: true
  validates :list, presence: true,length: {in: 1..500}
  
  belongs_to :plan
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true,length: {in: 1..100}
  
  belongs_to :user
  belongs_to :category
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,length: {in: 8..32}, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i} 
  validates :password_confirmation,length: {in: 8..32}
  
  has_many :plans
  has_many :todos
  has_many :questions
  has_many :answers
  #has_many :plan_todos, through: :plans, source: 'todo'
  has_many :tweets
  has_many :study_times
  has_many :qs

  has_secure_password
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
 
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categorys_path(@category),success:"カテゴリーの作成に成功しました"
    else
      flash.now[:danger] = "カテゴリーの作成に失敗しました"
      render 'new'
    end
  end
 
 
  def index
    @categorys = Category.all
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to categorys_path,success: 'カテゴリを更新しました'
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categorys_path,success: 'カテゴリを削除しました'
  end
  
  def qindex
    @categorys = Category.all
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  def index
    @qs = Q.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end
  
  def new
    @q = Q.new
    @category = Category.find(params[:category_id])
  end
  
  def create
    @q = Q.new(q_params)
    if @q.save
      redirect_to new_category_q_qcontent_path(category_id: @q.category_id, q_id: @q.id), success: '続いてクイズの内容の作成をしてください'
    else
      flash.now[:danger] = "クイズの作成に失敗しました"
      @category = @q.category
      render 'new'
    end
  end
  
  def show
    @q = Q.find(params[:id])
    @qcontents = @q.qcontents
    gon.qcontents = @qcontents
  end
  
  private
  def q_params
    params.require(:q).permit(:category_id, :user_id, :qtitle)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/qcontents_helper.rb
module QcontentsHelper
end

app/helpers/qs_helper.rb
module QsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categorys/edit.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @category, method: :patch do |f| %>
          <div class="form-group text-white">
            <%= f.label "題名" %>
            <%= f.text_area :name, class: 'form-control input-sm margin20'%>
          </div>
          <div class="col-md-4 col-md-offset-4">
            <%= f.submit '更新', class: 'btn btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categorys/index.html.erb
<div class="wrapper-stanard text-center">
  <div class="container container-standard">
    <div class="row">
      <h1 class="text-white margin40">学習カテゴリー　一覧</h1>
      <div class="col-md-offset-3 col-md-6 col-md-offset-3">
          <% @categorys.each do|category| %>
            <% if logged_in? && current_user.administrator? %>
              <%= link_to '編集', edit_category_path(category) %>
              <%= link_to '削除', category_path(category), method: :delete %>
              <%= link_to category.name,category_questions_path(category),class: 'btn btn-block btn-white' %>
            <% else %>
              <%= link_to category.name,category_questions_path(category),class: 'btn btn-block btn-white' %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categorys/new.html.erb
<div class="wrapper-stanard text-left">
  <div class="container container-standard">
    <div class="row">
        <%= form_for @category,url:categorys_path do |f| %>
        <div class="col-md-6 col-md-offset-3">
          <div class="form-group text-white">
            <%= f.label "学習カテゴリー作成",class:'margin20' %>
            <%= f.text_area :name, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-offset-5 col-md-2">  
            <%= f.submit '作成する', class: 'btn btn-block' %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/categorys/qindex.html.erb
<div class="wrapper-stanard text-center">
  <div class="container container-standard">
    <div class="row">
      <h1 class="text-white margin40">クイズ　カテゴリ</h1>
      <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <% @categorys.each do|category| %>
          <%= link_to category.name,category_qs_path(category),class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>